### ISSUE TITLE
[FEATURE] Add Frontend Routing

### ISSUE THREAD

**Issue by Doemuu** [Jenyus-Org/IMSForumPrototype#2]
# Overview

Add the Vue-Router plugin to the Vue project, as well as guards and routes to create the boilerplate for a SPA.

# Implementation Details

TBA.

**Comment by Dan6erbond** [comment]
@Doemuu add implementation details and further issue specifications.

**Comment by Dan6erbond** [comment]
Closed in #31 and previous commits.
